spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platform?useSSL=false
    username: postgres
    password: MRImaniac
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  devtools:
    restart:
      #热部署
      enabled: true
      additional-paths: src/main/java
  #      exclude: static/**
  mvc:
  #    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /upload/
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 400MB


server:
  port: 2222
springdoc:
  swagger-ui:
    path: /swagger-ui.html